# Generated by Django 5.2.8 on 2025-11-29 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artisanapi", "0002_cart_products_cart_services_cartitem_service_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="artisanapi.person"
            ),
        ),
    ]
